# Generated by Django 2.0.1 on 2018-01-16 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0002_auto_20170730_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='user.Profile'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='proposal.ProposalTopic'),
        ),
        migrations.AlterField(
            model_name='proposalcomment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_comments', to='user.Profile'),
        ),
        migrations.AlterField(
            model_name='topiccomment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_topic_comments', to='user.Profile'),
        ),
    ]
