BBBBBBB BBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBB
  XXXX
    XXX XXX
  XXXXX
  XXX
    XXXXX XXX XXX XXXX X XXXXXXXXX XXXXXXXXXX XXX X XXX XXXXXX XX XXXXX XXXXXXXXXX XXX XXXXX XXX XXX XXXXXXX XXXXXX XXXX XXX XXXXXXX XX XXXXXXXXX XXXXXXX XXXXXXXX XXXXX
  XXXX
  XXX
    XXXXXX XXXXXXXXXXXX
  XXXX
BBBBBBBB
