BBBBBBB BBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXX XXX XXXXXXXXXXXXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXBB BBBBBBBB BB BBBBBBBBBBBB XXXXXXBBBBBX XXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXBB BBBBBBBBBBBBB BB BBBBBBBBBBBB XXXXXXBBBBBX XXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXBB BBBBBBBBBBBB BB BBBBBBBBBBBB XXXXXXBBBBBX XXXXXXXXXXXXXXXX X XXX XXXXXXX XXXXXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXBB BBBBBBBBBBBBBB BB BBBBBBBBBBBB XXXXXXBBBBBX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXBB BBBBBBBBBBBBBB BB BBBBBBBBBBBB XXXXXXBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        BBBBB BBBBBBBBBB
        BBBBBBBB
      XXXXXX
    XXXXXX
  XXXXXX
BBBBBBBB
