# Generated by Django 2.0.1 on 2018-03-28 07:00

from django.db import migrations, models
import share.validators


class Migration(migrations.Migration):

    dependencies = [
        ('sentence', '0002_auto_20180116_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/%Y/%m/%d', validators=[share.validators.FileValidator(max_size=25165824)]),
        ),
        migrations.AddField(
            model_name='sentence',
            name='place',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentence',
            name='status',
            field=models.CharField(choices=[('SUG', 'Suggested'), ('EVL', 'Evaluated'), ('CFR', 'Confirmed'), ('RMV', 'Removed')], default=2, max_length=50),
            preserve_default=False,
        ),
    ]
