# Generated by Django 2.0.1 on 2018-03-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentence', '0003_auto_20180328_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='status',
            field=models.CharField(choices=[('SUG', 'Suggested'), ('EVL', 'Evaluated'), ('CFR', 'Confirmed'), ('RMV', 'Removed')], default='SUG', max_length=50),
        ),
    ]
