# Generated by Django 2.0.1 on 2018-03-29 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0002_language_default_variant'),
        ('sentence', '0005_historicalsentence_historicaltranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsentence',
            name='language',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='language.Language'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sentences', to='language.Language'),
        ),
    ]
