# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('reporter', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=150)),
                ('text', models.TextField()),
                ('kind', models.CharField(choices=[('tongue_twister', 'tongue twister'), ('song', 'song'), ('saying', 'saying'), ('poem', 'poem')], max_length=50)),
                ('creation_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
