# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitem',
            name='kind',
            field=models.CharField(choices=[('song', 'liad'), ('poem', 'gedihd'), ('tongue_twister', 'zunga breha'), ('saying', 'šbruh')], max_length=50),
        ),
    ]
