# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-04 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitem',
            name='kind',
            field=models.CharField(choices=[('saying', 'šbruh'), ('poem', 'gedihd'), ('song', 'liad'), ('tongue_twister', 'zunga breha')], max_length=50),
        ),
    ]
