# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-09 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20160909_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitem',
            name='kind',
            field=models.CharField(choices=[('saying', 'šbruh'), ('song', 'liad'), ('tongue_twister', 'zunga breha'), ('poem', 'gedihd')], max_length=50),
        ),
    ]
