# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-06 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20161004_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitem',
            name='kind',
            field=models.CharField(choices=[('song', 'liad'), ('tongue_twister', 'zunga breha'), ('saying', 'šbruh'), ('poem', 'gedihd')], max_length=50),
        ),
    ]
