# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20160710_0947'),
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitem',
            name='kind',
            field=models.CharField(choices=[('poem', 'gedihd'), ('saying', 'šbruh'), ('tongue_twister', 'zunga breha'), ('song', 'liad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.Profile'),
        ),
    ]
