# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20160710_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitem',
            name='kind',
            field=models.CharField(choices=[('saying', 'šbruh'), ('poem', 'gedihd'), ('tongue_twister', 'zunga breha'), ('song', 'liad')], max_length=50),
        ),
    ]
