# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-13 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20161006_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitem',
            name='kind',
            field=models.CharField(choices=[('tongue_twister', 'zunga breha'), ('poem', 'gedihd'), ('song', 'liad'), ('saying', 'šbruh')], max_length=50),
        ),
    ]
