# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-13 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_auto_20161013_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitem',
            name='kind',
            field=models.CharField(choices=[('poem', 'gedihd'), ('song', 'liad'), ('saying', 'šbruh'), ('tongue_twister', 'zunga breha')], max_length=50),
        ),
    ]
