# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-19 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_auto_20161013_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitem',
            name='kind',
            field=models.CharField(choices=[('poem', 'gedihd'), ('tongue_twister', 'zunga breha'), ('saying', 'šbruh'), ('song', 'liad')], max_length=50),
        ),
    ]
