# Generated by Django 2.0.1 on 2018-09-20 09:22

from django.db import migrations, models
import django.db.models.deletion


def fix_database(apps, schema_editor):
    Collection = apps.get_model('collection', 'Collection')
    cols = Collection.objects.filter(type="help")
    for col in cols:
        col.type = 1
        col.save()


def create_dummy_collection_type(apps, schema_editor):
    CollectionType = apps.get_model('collection', 'CollectionType')
    CollectionType.objects.create(name="help")


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_auto_20180116_2012'),
    ]

    operations = [
        migrations.RunPython(fix_database, reverse_code=migrations.RunPython.noop),

        migrations.CreateModel(
            name='CollectionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RunPython(create_dummy_collection_type, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='collection',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_items', to='collection.CollectionType'),
        ),
        migrations.AlterField(
            model_name='historicalcollection',
            name='type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='collection.CollectionType'),
        ),
    ]
