# Generated by Django 2.0.1 on 2018-10-08 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_auto_20180920_0922'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('title', 'text', 'type')},
        ),
    ]
