# Generated by Django 2.0.1 on 2018-02-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='default_variant',
            field=models.CharField(blank=True, help_text="Variant of the language such as 'bv_DA' for Danube Bavarian", max_length=5),
        ),
    ]
