BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB BBBBBBBBBBBB
BBBBB BBBBBBBBBBXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBX XXBBBBBBBB
BBBBB BBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBB BBBBBBBBXX XXXXXXXX gettext('Documentation') XXXX X BBBBB  gettext('Change password')  X XX XXXXXXBBB BBBBBBBBBBBBBBXX gettext('Log out') XXXXBBBBBBBB
BBBBB BBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXX
XX XXXXXXBBB BBBBBBBBBBBBBXX gettext('Home') XXXX
XXXXXXXX  gettext('Password change') 
XXXXXX
BBBBBBBB

BBBBB BBBBBBBBBBBBB
BBBBB BBBBBBBBBBBBBXXXXXXXXXBBBBBBBB

BBBBB BBBBBBBXXXX XXXXXXXXXXXXXXXXXX

XXXXX XXXXXXXXXXXXXXBBBBBBBBBB
XXXXX
BB BBBBBBBBBBB
    XX XXXXXXXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBBBBBBBBBB BB B gettext('Please correct the error below.') BBBB gettext('Please correct the errors below.') BBBBB
    XXXX
BBBBB


XXX gettext("Please enter your old password, for security's sake, and then enter your new password twice so we can verify you typed it in correctly.") XXXX

XXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXX

XXXX XXXXXXXXXXXXXXXXX
    
     
XXXXXX

XXXX XXXXXXXXXXXXXXXXX
    
     
    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XX XXXXXXXXXXXXXFFFFXXXX
    BBBBB
XXXXXX

XXXX XXXXXXXXXXXXXXXXX

     
    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XX XXXXXXXXXXXXXFFFFXXXX
    BBBBB
XXXXXX

XXXXXXXXXXX

XXXX XXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXX XXXXXXX gettext('Change my password') X XXXXXXXXXXXXXXX XX
XXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXX
XXXXXXXXXXXXX

BBBBBBBB
