BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBBB BBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBB BBBBBBBBXX XXXXXXXX gettext('Documentation') XXXX X BBBBB gettext('Change password')  X XX XXXXXXBBB BBBBBBBBBBBBBBXX gettext('Log out') XXXXBBBBBBBB
BBBBB BBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXX
XX XXXXXXBBB BBBBBBBBBBBBBXX gettext('Home') XXXX
XXXXXXXX  gettext('Password change') 
XXXXXX
BBBBBBBB

BBBBB BBBBBBBBBBBBB
BBBBB BBBBBBBBBBBBBXXXXXXXXXBBBBBBBB
BBBBB BBBBBBB
XXX gettext('Your password was changed.') XXXX
BBBBBBBB
