BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXX
XX XXXXXXBBB BBBBBBBBBBBBBXX gettext('Home') XXXX
XXXXXXXX  gettext('Password reset confirmation') 
XXXXXX
BBBBBBBB

BBBBB BBBBBBBBBBBBB
BBBBB BBBBBBBBBBBBBXXXXXXXXXBBBBBBBB
BBBBB BBBBBBB

BB BBBBBBBBB

XXX gettext('Please enter your new password twice so we can verify you typed it in correctly.') XXXX

XXXXX XXXXXXXXXXXXXXBBBBBBBBBB

XX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext('New password:') XXXXXXXXXXXX

XX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext('Confirm password:') XXXXXXXXXXXX
XXXXXXXXX XXXXXXXXXXXXX XXXXXXX gettext('Change my password') X XXXXXX
XXXXXXX

BBBB

XXX gettext('The password reset link was invalid, possibly because it has already been used.  Please request a new password reset.') XXXX

BBBBB

BBBBBBBB
