BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXX
XX XXXXXXBBB BBBBBBBBBBBBBXX gettext('Home') XXXX
XXXXXXXX  gettext('Password reset') 
XXXXXX
BBBBBBBB

BBBBB BBBBBBBBBBBBB
BBBBB BBBBBBBBBBBBBXXXXXXXXXBBBBBBBB
BBBBB BBBBBBB

XXX gettext("Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.") XXXX

XXXXX XXXXXXXXXXXXXXBBBBBBBBBB

XXXXXXXXX XXXXXXXXXXXXXXX gettext('Email address:') XXXXXXXX  XXXXXX XXXXXXXXXXXXX XXXXXXX gettext('Reset my password') X XXXXXX
XXXXXXX

BBBBBBBB
