BBBBBBB BBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXX
          
        XXXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXX
          XXXXX 
        XXXXX
        XXX
          
        XXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXX
          
        XXXX
        XXX
          
        XXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBXXXXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
BBBBBBBB
