BBBBBBB BBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBB
  XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXXXXXX
    BBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
          XXXX
            XXXXX 
          XXXXX
          XXX
            XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXXX
BBBBBBBB
