BBBBBBB BBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXX
          
        XXXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXX
          
        XXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXX
          XXXXXXX
            XXXX
              XXXX
                XXXXX
              XXXXX
              XXXX
                XXXXXXX
              XXXXX
            XXXXX
          XXXXXXXX
          XX XXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXX
          XXXXXXX
            BBB BBBBBBBB BB BBBBBBBBB
              XXXX
                XXXX
                  XX XXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBXXXXXX
                XXXXX
                XXXX
                  
                XXXXX
              XXXXX
            BBBBBB
          XXXXXXXX
        XXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
BBBBBBBB
