# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-09 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import word.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('language', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('standard', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('SUG', 'Suggested'), ('CFR', 'Confirmed'), ('RMV', 'Removed')], max_length=50)),
                ('audio', models.FileField(blank=True, null=True, upload_to=word.models.audio_path)),
                ('version', models.IntegerField(default=1)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language.Language')),
                ('synonyms', models.ManyToManyField(blank=True, related_name='_word_synonyms_+', to='word.Word')),
                ('tags', models.ManyToManyField(blank=True, to='word.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WordHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('standard', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('SUG', 'Suggested'), ('CFR', 'Confirmed'), ('RMV', 'Removed')], max_length=50)),
                ('audio', models.FileField(blank=True, null=True, upload_to=word.models.audio_path)),
                ('version', models.IntegerField(default=1)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language.Language')),
                ('old', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word.Word')),
                ('synonyms', models.ManyToManyField(blank=True, related_name='_wordhistory_synonyms_+', to='word.WordHistory')),
                ('tags', models.ManyToManyField(blank=True, to='word.Tag')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
