# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-04 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import word.models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('short_desc', models.CharField(default='', max_length=100)),
                ('desc', models.TextField(default='')),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to=word.models.audio_path)),
                ('tags', models.ManyToManyField(blank=True, to='word.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='word',
            name='language',
        ),
        migrations.RemoveField(
            model_name='word',
            name='standard',
        ),
        migrations.RemoveField(
            model_name='wordhistory',
            name='language',
        ),
        migrations.RemoveField(
            model_name='wordhistory',
            name='standard',
        ),
        migrations.RemoveField(
            model_name='wordhistory',
            name='synonyms',
        ),
        migrations.AddField(
            model_name='word',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='word',
            name='short_desc',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='wordhistory',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='wordhistory',
            name='short_desc',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='word',
            name='status',
            field=models.CharField(choices=[('SUG', 'Suggested'), ('EVL', 'Evaluated'), ('CFR', 'Confirmed'), ('RMV', 'Removed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='wordhistory',
            name='status',
            field=models.CharField(choices=[('SUG', 'Suggested'), ('EVL', 'Evaluated'), ('CFR', 'Confirmed'), ('RMV', 'Removed')], max_length=50),
        ),
        migrations.AddField(
            model_name='word',
            name='translations',
            field=models.ManyToManyField(blank=True, related_name='words', to='word.Translation'),
        ),
    ]
