# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltranslation',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalword',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
