# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-06 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0001_initial'),
        ('word', '0002_auto_20161004_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(max_length=150)),
                ('extended', models.TextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language.Language')),
            ],
        ),
        migrations.RemoveField(
            model_name='translation',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='word',
            name='short_desc',
        ),
        migrations.RemoveField(
            model_name='word',
            name='synonyms',
        ),
        migrations.RemoveField(
            model_name='wordhistory',
            name='short_desc',
        ),
        migrations.AddField(
            model_name='word',
            name='language',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='language.Language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wordhistory',
            name='language',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='language.Language'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='word',
            name='desc',
        ),
        migrations.AlterField(
            model_name='word',
            name='translations',
            field=models.ManyToManyField(blank=True, related_name='_word_translations_+', to='word.Word'),
        ),
        migrations.AlterField(
            model_name='word',
            name='version',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='wordhistory',
            name='desc',
        ),
        migrations.AlterField(
            model_name='wordhistory',
            name='version',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Translation',
        ),
        migrations.AddField(
            model_name='word',
            name='desc',
            field=models.ManyToManyField(blank=True, to='word.Description'),
        ),
        migrations.AddField(
            model_name='wordhistory',
            name='desc',
            field=models.ManyToManyField(blank=True, to='word.Description'),
        ),
    ]
