# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-13 17:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('language', '0001_initial'),
        ('word', '0003_auto_20161006_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalWord',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('creation_date', models.DateField(blank=True, editable=False)),
                ('audio', models.TextField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('SUG', 'Suggested'), ('EVL', 'Evaluated'), ('CFR', 'Confirmed'), ('RMV', 'Removed')], max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='language.Language')),
            ],
            options={
                'get_latest_by': 'history_date',
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical word',
            },
        ),
        migrations.RemoveField(
            model_name='wordhistory',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='wordhistory',
            name='language',
        ),
        migrations.RemoveField(
            model_name='wordhistory',
            name='old',
        ),
        migrations.RemoveField(
            model_name='wordhistory',
            name='tags',
        ),
        migrations.DeleteModel(
            name='WordHistory',
        ),
    ]
