# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0003_collection_historicalcollection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='reporter',
        ),
        migrations.RemoveField(
            model_name='historicalcollection',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcollection',
            name='reporter',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='HistoricalCollection',
        ),
    ]
