# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0006_wordlocation_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltranslation',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaltranslation',
            name='language',
        ),
        migrations.RemoveField(
            model_name='historicaltranslation',
            name='translation',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='language',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='translation',
        ),
        migrations.AddField(
            model_name='historicalword',
            name='wiktionary_link',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='word',
            name='wiktionary_link',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='wordversion',
            name='link',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.DeleteModel(
            name='HistoricalTranslation',
        ),
        migrations.DeleteModel(
            name='Translation',
        ),
    ]
