# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-19 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0007_auto_20161119_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bavarianword',
            name='language',
        ),
        migrations.RemoveField(
            model_name='foreignword',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='foreignword',
            name='upvotes',
        ),
        migrations.RemoveField(
            model_name='historicalbavarianword',
            name='language',
        ),
        migrations.RemoveField(
            model_name='historicalforeignword',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='historicalforeignword',
            name='upvotes',
        ),
    ]
