# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_place'),
        ('word', '0008_auto_20170806_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalword',
            name='submitter',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.Profile'),
        ),
        migrations.AddField(
            model_name='word',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_words', to='user.Profile'),
            preserve_default=False,
        ),
    ]
