# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0009_auto_20170806_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalword',
            name='ipa',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='word',
            name='ipa',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='historicalword',
            name='word',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=150),
        ),
    ]
