# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0010_auto_20170811_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='wordversion',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
