# Generated by Django 2.0.1 on 2018-01-16 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0013_auto_20170812_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descriptions', to='language.Language'),
        ),
        migrations.AlterField(
            model_name='word',
            name='submitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_words', to='user.Profile'),
        ),
        migrations.AlterField(
            model_name='word',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='words', to='word.WordVersion'),
        ),
        migrations.AlterField(
            model_name='wordlocation',
            name='submitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Profile'),
        ),
        migrations.AlterField(
            model_name='wordversion',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='language.Language'),
        ),
    ]
