# Generated by Django 2.0.1 on 2018-02-20 21:48

from django.db import migrations, models

import share.validators


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0014_auto_20180116_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalword',
            name='audio',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[
                share.validators.FileValidator(max_size=25165824)]),
        ),
        migrations.AlterField(
            model_name='word',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to="audio/%Y/%m/%d", validators=[
                share.validators.FileValidator(max_size=25165824)]),
        ),
    ]
