# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-07 15:59
from __future__ import unicode_literals

import dictionary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('upvotes', models.IntegerField()),
                ('downvotes', models.IntegerField()),
                ('standard', models.BooleanField()),
                ('status', models.CharField(choices=[('SUG', 'Suggested'), ('CFR', 'Confirmed'), ('RMV', 'Removed')], max_length=50)),
                ('audio', models.FileField(blank=True, null=True, upload_to=dictionary.models.audio_path)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Language')),
                ('synonyms', models.ManyToManyField(blank=True, related_name='_word_synonyms_+', to='dictionary.Word')),
                ('tags', models.ManyToManyField(blank=True, to='dictionary.Tag')),
            ],
        ),
    ]
