# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 18:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictionary', '0002_auto_20160416_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_by', to=settings.AUTH_USER_MODEL)),
                ('first_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_word', to='dictionary.Word')),
                ('second_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_word', to='dictionary.Word')),
            ],
        ),
    ]
