# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_wordrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
