# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlanguage',
            name='proficiency',
            field=models.CharField(choices=[('beginner', 'beginner'), ('novice', 'novice'), ('intermediate', 'intermediate'), ('advanced', 'advanced'), ('fluent', 'fluent'), ('native', 'native')], default='beginner', max_length=25),
        ),
    ]
