# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='max_suggest_words_per_day',
            field=models.IntegerField(default=10),
        ),
    ]
