# Generated by Django 2.0.1 on 2018-03-15 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_profile_email_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_confirmed',
        ),
    ]
